### ISSUE TITLE
Where is the TestApp?

### ISSUE THREAD

**Issue by taoeternal2018** [arduosoft/HubLink.Net#1]
Hi Daniele, thanks to your remarkable work, that's really cool!

However, I can't find the TestApp you mentioned in article "A Simple Remote Logging Platform". So I'm a little bit confused about class WebTarget , could you please explain it to me? Thanks a lot.

**Comment by zeppaman** [comment]
Hi @taoeternal2018 ,
When I wrote the article I created the POC for hublink. We worked to make this POC working so many detail since its first implementation will change. In example, the original project was splitted into server part and client one, taking in account many client implementation could be needed.

Inside this repo you can find core classes and log implementation:
NLog:HubLink.Net/WLog.Loggers/WebTarget.cs
Log4net:HubLink.Net/WLog.Clients.Log4Net/WebAppender.cs

The structure is:
WLog.Clients: all stuff shared (remote dictionary, common logging features...)
WLog.Clients.NLog: log for net specific classes
WLog.Clients.Log4Net: nlog specific classes


Into WebTarget class you just have to implement how logs are handled, in my case I send data using and http call to a rest service. Registering the web target, Nlog engine will add your target to the application and send logs to it basing on settings. 

Let me know if I wasn't clear or you have some specific question.

Thank you for interesting in this project.

**Comment by taoeternal2018** [comment]
hi @zeppaman ,
Thank you so much for your timely respond. I noticed the codes  inside the zip file are quite different from those in the repo. Just got complete codes with git, cheers~~~

**Comment by zeppaman** [comment]
that's great! Enjoy the code and let me know what do you think about.
